### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by wodouxiangxiaole** [Jiaxin-Lu/Jigsaw#2]
Hi, 

Thanks for the great work. May I ask do you prepare release the visualization code?

**Comment by Jiaxin-Lu** [comment]
We intend to publish the training visualization on Weight & Bias. However, the code generating the final output, due to its incompatibility with the current environment (the issue of open3d), was executed independently. Consequently, we do not have plans to release the visualization of the final output. Thank you for your understanding.
