### ISSUE TITLE
logs didn't include metrics like PA/SCD as mentioned in your paper

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [Jiaxin-Lu/Jigsaw#8]
hello, lu

When I tried to train your code, I found that its logs didn't include metrics like PA/SCD as shown in your paper.
is there something wrong with me?

Ruiyuan

my logs:
![image](https://github.com/user-attachments/assets/88d1294e-4bcb-4d8e-b3ed-1d9d7a9d8b24)
![image](https://github.com/user-attachments/assets/3faedbfc-f969-4c19-83af-56a103a6a258)

**Comment by Jiaxin-Lu** [comment]
The training only includes the segmentation and multi-part matching. In order to get the assembly result, it still requires global alignment. This is not written in our training code as it is an off-the-shelf non-trainable method. Therefore, You should run the evaluation separately to get the PA/SCD results as you want.
